spring.application.name=Backend

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

server.port=8080

ml.service.url=http://localhost:5000

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000